/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CarrierRouteImport } from './routes/carrier'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as OperatorIndexRouteImport } from './routes/operator/index'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as OperatorPendingRouteImport } from './routes/operator/pending'
import { Route as OperatorCapacityRouteImport } from './routes/operator/capacity'
import { Route as OperatorBookingsRouteImport } from './routes/operator/bookings'
import { Route as CarrierTrucksRouteImport } from './routes/carrier/trucks'
import { Route as CarrierContainersRouteImport } from './routes/carrier/containers'
import { Route as CarrierBookingsRouteImport } from './routes/carrier/bookings'
import { Route as AdminTrucksRouteImport } from './routes/admin/trucks'
import { Route as AdminTerminalsRouteImport } from './routes/admin/terminals'
import { Route as AdminGatesRouteImport } from './routes/admin/gates'
import { Route as AdminCarriersRouteImport } from './routes/admin/carriers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierRoute = CarrierRouteImport.update({
  id: '/carrier',
  path: '/carrier',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const OperatorPendingRoute = OperatorPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorCapacityRoute = OperatorCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorBookingsRoute = OperatorBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OperatorRoute,
} as any)
const CarrierTrucksRoute = CarrierTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierContainersRoute = CarrierContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierBookingsRoute = CarrierBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CarrierRoute,
} as any)
const AdminTrucksRoute = AdminTrucksRouteImport.update({
  id: '/admin/trucks',
  path: '/admin/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerminalsRoute = AdminTerminalsRouteImport.update({
  id: '/admin/terminals',
  path: '/admin/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatesRoute = AdminGatesRouteImport.update({
  id: '/admin/gates',
  path: '/admin/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarriersRoute = AdminCarriersRouteImport.update({
  id: '/admin/carriers',
  path: '/admin/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/carrier': typeof CarrierRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/carrier/bookings': typeof CarrierBookingsRoute
  '/carrier/containers': typeof CarrierContainersRoute
  '/carrier/trucks': typeof CarrierTrucksRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/capacity': typeof OperatorCapacityRoute
  '/operator/pending': typeof OperatorPendingRoute
  '/operator/': typeof OperatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/carrier': typeof CarrierRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/carrier/bookings': typeof CarrierBookingsRoute
  '/carrier/containers': typeof CarrierContainersRoute
  '/carrier/trucks': typeof CarrierTrucksRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/capacity': typeof OperatorCapacityRoute
  '/operator/pending': typeof OperatorPendingRoute
  '/': typeof ChatIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/carrier': typeof CarrierRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/carrier/bookings': typeof CarrierBookingsRoute
  '/carrier/containers': typeof CarrierContainersRoute
  '/carrier/trucks': typeof CarrierTrucksRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/capacity': typeof OperatorCapacityRoute
  '/operator/pending': typeof OperatorPendingRoute
  '/_chat/': typeof ChatIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrier'
    | '/login'
    | '/operator'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/carrier/bookings'
    | '/carrier/containers'
    | '/carrier/trucks'
    | '/operator/bookings'
    | '/operator/capacity'
    | '/operator/pending'
    | '/operator/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/carrier'
    | '/login'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/carrier/bookings'
    | '/carrier/containers'
    | '/carrier/trucks'
    | '/operator/bookings'
    | '/operator/capacity'
    | '/operator/pending'
    | '/'
    | '/operator'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_chat'
    | '/carrier'
    | '/login'
    | '/operator'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/carrier/bookings'
    | '/carrier/containers'
    | '/carrier/trucks'
    | '/operator/bookings'
    | '/operator/capacity'
    | '/operator/pending'
    | '/_chat/'
    | '/operator/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  CarrierRoute: typeof CarrierRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  AdminCarriersRoute: typeof AdminCarriersRoute
  AdminGatesRoute: typeof AdminGatesRoute
  AdminTerminalsRoute: typeof AdminTerminalsRoute
  AdminTrucksRoute: typeof AdminTrucksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier': {
      id: '/carrier'
      path: '/carrier'
      fullPath: '/carrier'
      preLoaderRoute: typeof CarrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/operator/pending': {
      id: '/operator/pending'
      path: '/pending'
      fullPath: '/operator/pending'
      preLoaderRoute: typeof OperatorPendingRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/capacity': {
      id: '/operator/capacity'
      path: '/capacity'
      fullPath: '/operator/capacity'
      preLoaderRoute: typeof OperatorCapacityRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/bookings': {
      id: '/operator/bookings'
      path: '/bookings'
      fullPath: '/operator/bookings'
      preLoaderRoute: typeof OperatorBookingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/carrier/trucks': {
      id: '/carrier/trucks'
      path: '/trucks'
      fullPath: '/carrier/trucks'
      preLoaderRoute: typeof CarrierTrucksRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/containers': {
      id: '/carrier/containers'
      path: '/containers'
      fullPath: '/carrier/containers'
      preLoaderRoute: typeof CarrierContainersRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/bookings': {
      id: '/carrier/bookings'
      path: '/bookings'
      fullPath: '/carrier/bookings'
      preLoaderRoute: typeof CarrierBookingsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/admin/trucks': {
      id: '/admin/trucks'
      path: '/admin/trucks'
      fullPath: '/admin/trucks'
      preLoaderRoute: typeof AdminTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terminals': {
      id: '/admin/terminals'
      path: '/admin/terminals'
      fullPath: '/admin/terminals'
      preLoaderRoute: typeof AdminTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gates': {
      id: '/admin/gates'
      path: '/admin/gates'
      fullPath: '/admin/gates'
      preLoaderRoute: typeof AdminGatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/carriers': {
      id: '/admin/carriers'
      path: '/admin/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AdminCarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface CarrierRouteChildren {
  CarrierBookingsRoute: typeof CarrierBookingsRoute
  CarrierContainersRoute: typeof CarrierContainersRoute
  CarrierTrucksRoute: typeof CarrierTrucksRoute
}

const CarrierRouteChildren: CarrierRouteChildren = {
  CarrierBookingsRoute: CarrierBookingsRoute,
  CarrierContainersRoute: CarrierContainersRoute,
  CarrierTrucksRoute: CarrierTrucksRoute,
}

const CarrierRouteWithChildren =
  CarrierRoute._addFileChildren(CarrierRouteChildren)

interface OperatorRouteChildren {
  OperatorBookingsRoute: typeof OperatorBookingsRoute
  OperatorCapacityRoute: typeof OperatorCapacityRoute
  OperatorPendingRoute: typeof OperatorPendingRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorBookingsRoute: OperatorBookingsRoute,
  OperatorCapacityRoute: OperatorCapacityRoute,
  OperatorPendingRoute: OperatorPendingRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  CarrierRoute: CarrierRouteWithChildren,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  AdminCarriersRoute: AdminCarriersRoute,
  AdminGatesRoute: AdminGatesRoute,
  AdminTerminalsRoute: AdminTerminalsRoute,
  AdminTrucksRoute: AdminTrucksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
