/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppThreadIdRouteImport } from './routes/_app/$threadId'
import { Route as AppOperatorIndexRouteImport } from './routes/_app/operator/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOperatorPendingRouteImport } from './routes/_app/operator/pending'
import { Route as AppOperatorCapacityRouteImport } from './routes/_app/operator/capacity'
import { Route as AppOperatorBookingsRouteImport } from './routes/_app/operator/bookings'
import { Route as AppOperatorAnalyticsRouteImport } from './routes/_app/operator/analytics'
import { Route as AppCarrierTrucksRouteImport } from './routes/_app/carrier/trucks'
import { Route as AppCarrierContainersRouteImport } from './routes/_app/carrier/containers'
import { Route as AppCarrierBookingsRouteImport } from './routes/_app/carrier/bookings'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTrucksRouteImport } from './routes/_app/admin/trucks'
import { Route as AppAdminTerminalsRouteImport } from './routes/_app/admin/terminals'
import { Route as AppAdminOperatorsRouteImport } from './routes/_app/admin/operators'
import { Route as AppAdminGatesRouteImport } from './routes/_app/admin/gates'
import { Route as AppAdminConfigRouteImport } from './routes/_app/admin/config'
import { Route as AppAdminCarriersRouteImport } from './routes/_app/admin/carriers'
import { Route as AppAdminAuditLogsRouteImport } from './routes/_app/admin/audit-logs'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadIdRoute = AppThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorIndexRoute = AppOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOperatorPendingRoute = AppOperatorPendingRouteImport.update({
  id: '/operator/pending',
  path: '/operator/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorCapacityRoute = AppOperatorCapacityRouteImport.update({
  id: '/operator/capacity',
  path: '/operator/capacity',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorBookingsRoute = AppOperatorBookingsRouteImport.update({
  id: '/operator/bookings',
  path: '/operator/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorAnalyticsRoute = AppOperatorAnalyticsRouteImport.update({
  id: '/operator/analytics',
  path: '/operator/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCarrierTrucksRoute = AppCarrierTrucksRouteImport.update({
  id: '/carrier/trucks',
  path: '/carrier/trucks',
  getParentRoute: () => AppRoute,
} as any)
const AppCarrierContainersRoute = AppCarrierContainersRouteImport.update({
  id: '/carrier/containers',
  path: '/carrier/containers',
  getParentRoute: () => AppRoute,
} as any)
const AppCarrierBookingsRoute = AppCarrierBookingsRouteImport.update({
  id: '/carrier/bookings',
  path: '/carrier/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTrucksRoute = AppAdminTrucksRouteImport.update({
  id: '/admin/trucks',
  path: '/admin/trucks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTerminalsRoute = AppAdminTerminalsRouteImport.update({
  id: '/admin/terminals',
  path: '/admin/terminals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOperatorsRoute = AppAdminOperatorsRouteImport.update({
  id: '/admin/operators',
  path: '/admin/operators',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGatesRoute = AppAdminGatesRouteImport.update({
  id: '/admin/gates',
  path: '/admin/gates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfigRoute = AppAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCarriersRoute = AppAdminCarriersRouteImport.update({
  id: '/admin/carriers',
  path: '/admin/carriers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$threadId': typeof AppThreadIdRoute
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/carriers': typeof AppAdminCarriersRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/gates': typeof AppAdminGatesRoute
  '/admin/operators': typeof AppAdminOperatorsRoute
  '/admin/terminals': typeof AppAdminTerminalsRoute
  '/admin/trucks': typeof AppAdminTrucksRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/carrier/bookings': typeof AppCarrierBookingsRoute
  '/carrier/containers': typeof AppCarrierContainersRoute
  '/carrier/trucks': typeof AppCarrierTrucksRoute
  '/operator/analytics': typeof AppOperatorAnalyticsRoute
  '/operator/bookings': typeof AppOperatorBookingsRoute
  '/operator/capacity': typeof AppOperatorCapacityRoute
  '/operator/pending': typeof AppOperatorPendingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/operator/': typeof AppOperatorIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$threadId': typeof AppThreadIdRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/carriers': typeof AppAdminCarriersRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/gates': typeof AppAdminGatesRoute
  '/admin/operators': typeof AppAdminOperatorsRoute
  '/admin/terminals': typeof AppAdminTerminalsRoute
  '/admin/trucks': typeof AppAdminTrucksRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/carrier/bookings': typeof AppCarrierBookingsRoute
  '/carrier/containers': typeof AppCarrierContainersRoute
  '/carrier/trucks': typeof AppCarrierTrucksRoute
  '/operator/analytics': typeof AppOperatorAnalyticsRoute
  '/operator/bookings': typeof AppOperatorBookingsRoute
  '/operator/capacity': typeof AppOperatorCapacityRoute
  '/operator/pending': typeof AppOperatorPendingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/operator': typeof AppOperatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$threadId': typeof AppThreadIdRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/_app/admin/carriers': typeof AppAdminCarriersRoute
  '/_app/admin/config': typeof AppAdminConfigRoute
  '/_app/admin/gates': typeof AppAdminGatesRoute
  '/_app/admin/operators': typeof AppAdminOperatorsRoute
  '/_app/admin/terminals': typeof AppAdminTerminalsRoute
  '/_app/admin/trucks': typeof AppAdminTrucksRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/carrier/bookings': typeof AppCarrierBookingsRoute
  '/_app/carrier/containers': typeof AppCarrierContainersRoute
  '/_app/carrier/trucks': typeof AppCarrierTrucksRoute
  '/_app/operator/analytics': typeof AppOperatorAnalyticsRoute
  '/_app/operator/bookings': typeof AppOperatorBookingsRoute
  '/_app/operator/capacity': typeof AppOperatorCapacityRoute
  '/_app/operator/pending': typeof AppOperatorPendingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/operator/': typeof AppOperatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$threadId'
    | '/settings'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/carriers'
    | '/admin/config'
    | '/admin/gates'
    | '/admin/operators'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/admin/users'
    | '/carrier/bookings'
    | '/carrier/containers'
    | '/carrier/trucks'
    | '/operator/analytics'
    | '/operator/bookings'
    | '/operator/capacity'
    | '/operator/pending'
    | '/api/auth/$'
    | '/admin/'
    | '/operator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$threadId'
    | '/settings'
    | '/'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/carriers'
    | '/admin/config'
    | '/admin/gates'
    | '/admin/operators'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/admin/users'
    | '/carrier/bookings'
    | '/carrier/containers'
    | '/carrier/trucks'
    | '/operator/analytics'
    | '/operator/bookings'
    | '/operator/capacity'
    | '/operator/pending'
    | '/api/auth/$'
    | '/admin'
    | '/operator'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$threadId'
    | '/_app/settings'
    | '/_app/'
    | '/_app/admin/analytics'
    | '/_app/admin/audit-logs'
    | '/_app/admin/carriers'
    | '/_app/admin/config'
    | '/_app/admin/gates'
    | '/_app/admin/operators'
    | '/_app/admin/terminals'
    | '/_app/admin/trucks'
    | '/_app/admin/users'
    | '/_app/carrier/bookings'
    | '/_app/carrier/containers'
    | '/_app/carrier/trucks'
    | '/_app/operator/analytics'
    | '/_app/operator/bookings'
    | '/_app/operator/capacity'
    | '/_app/operator/pending'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/operator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$threadId': {
      id: '/_app/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof AppThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator/': {
      id: '/_app/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof AppOperatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operator/pending': {
      id: '/_app/operator/pending'
      path: '/operator/pending'
      fullPath: '/operator/pending'
      preLoaderRoute: typeof AppOperatorPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator/capacity': {
      id: '/_app/operator/capacity'
      path: '/operator/capacity'
      fullPath: '/operator/capacity'
      preLoaderRoute: typeof AppOperatorCapacityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator/bookings': {
      id: '/_app/operator/bookings'
      path: '/operator/bookings'
      fullPath: '/operator/bookings'
      preLoaderRoute: typeof AppOperatorBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator/analytics': {
      id: '/_app/operator/analytics'
      path: '/operator/analytics'
      fullPath: '/operator/analytics'
      preLoaderRoute: typeof AppOperatorAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carrier/trucks': {
      id: '/_app/carrier/trucks'
      path: '/carrier/trucks'
      fullPath: '/carrier/trucks'
      preLoaderRoute: typeof AppCarrierTrucksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carrier/containers': {
      id: '/_app/carrier/containers'
      path: '/carrier/containers'
      fullPath: '/carrier/containers'
      preLoaderRoute: typeof AppCarrierContainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carrier/bookings': {
      id: '/_app/carrier/bookings'
      path: '/carrier/bookings'
      fullPath: '/carrier/bookings'
      preLoaderRoute: typeof AppCarrierBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/trucks': {
      id: '/_app/admin/trucks'
      path: '/admin/trucks'
      fullPath: '/admin/trucks'
      preLoaderRoute: typeof AppAdminTrucksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/terminals': {
      id: '/_app/admin/terminals'
      path: '/admin/terminals'
      fullPath: '/admin/terminals'
      preLoaderRoute: typeof AppAdminTerminalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/operators': {
      id: '/_app/admin/operators'
      path: '/admin/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AppAdminOperatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/gates': {
      id: '/_app/admin/gates'
      path: '/admin/gates'
      fullPath: '/admin/gates'
      preLoaderRoute: typeof AppAdminGatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/config': {
      id: '/_app/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AppAdminConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/carriers': {
      id: '/_app/admin/carriers'
      path: '/admin/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AppAdminCarriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit-logs': {
      id: '/_app/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppThreadIdRoute: typeof AppThreadIdRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminCarriersRoute: typeof AppAdminCarriersRoute
  AppAdminConfigRoute: typeof AppAdminConfigRoute
  AppAdminGatesRoute: typeof AppAdminGatesRoute
  AppAdminOperatorsRoute: typeof AppAdminOperatorsRoute
  AppAdminTerminalsRoute: typeof AppAdminTerminalsRoute
  AppAdminTrucksRoute: typeof AppAdminTrucksRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppCarrierBookingsRoute: typeof AppCarrierBookingsRoute
  AppCarrierContainersRoute: typeof AppCarrierContainersRoute
  AppCarrierTrucksRoute: typeof AppCarrierTrucksRoute
  AppOperatorAnalyticsRoute: typeof AppOperatorAnalyticsRoute
  AppOperatorBookingsRoute: typeof AppOperatorBookingsRoute
  AppOperatorCapacityRoute: typeof AppOperatorCapacityRoute
  AppOperatorPendingRoute: typeof AppOperatorPendingRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppOperatorIndexRoute: typeof AppOperatorIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppThreadIdRoute: AppThreadIdRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminCarriersRoute: AppAdminCarriersRoute,
  AppAdminConfigRoute: AppAdminConfigRoute,
  AppAdminGatesRoute: AppAdminGatesRoute,
  AppAdminOperatorsRoute: AppAdminOperatorsRoute,
  AppAdminTerminalsRoute: AppAdminTerminalsRoute,
  AppAdminTrucksRoute: AppAdminTrucksRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppCarrierBookingsRoute: AppCarrierBookingsRoute,
  AppCarrierContainersRoute: AppCarrierContainersRoute,
  AppCarrierTrucksRoute: AppCarrierTrucksRoute,
  AppOperatorAnalyticsRoute: AppOperatorAnalyticsRoute,
  AppOperatorBookingsRoute: AppOperatorBookingsRoute,
  AppOperatorCapacityRoute: AppOperatorCapacityRoute,
  AppOperatorPendingRoute: AppOperatorPendingRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppOperatorIndexRoute: AppOperatorIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
