/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvexShowcaseRouteImport } from './routes/convex-showcase'
import { Route as AiBookingRouteImport } from './routes/ai-booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTrucksRouteImport } from './routes/admin/trucks'
import { Route as AdminTerminalsRouteImport } from './routes/admin/terminals'
import { Route as AdminGatesRouteImport } from './routes/admin/gates'
import { Route as AdminCarriersRouteImport } from './routes/admin/carriers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexShowcaseRoute = ConvexShowcaseRouteImport.update({
  id: '/convex-showcase',
  path: '/convex-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBookingRoute = AiBookingRouteImport.update({
  id: '/ai-booking',
  path: '/ai-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrucksRoute = AdminTrucksRouteImport.update({
  id: '/admin/trucks',
  path: '/admin/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerminalsRoute = AdminTerminalsRouteImport.update({
  id: '/admin/terminals',
  path: '/admin/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatesRoute = AdminGatesRouteImport.update({
  id: '/admin/gates',
  path: '/admin/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarriersRoute = AdminCarriersRouteImport.update({
  id: '/admin/carriers',
  path: '/admin/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-booking': typeof AiBookingRoute
  '/convex-showcase': typeof ConvexShowcaseRoute
  '/dashboard': typeof DashboardRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-booking': typeof AiBookingRoute
  '/convex-showcase': typeof ConvexShowcaseRoute
  '/dashboard': typeof DashboardRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-booking': typeof AiBookingRoute
  '/convex-showcase': typeof ConvexShowcaseRoute
  '/dashboard': typeof DashboardRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/gates': typeof AdminGatesRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-booking'
    | '/convex-showcase'
    | '/dashboard'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-booking'
    | '/convex-showcase'
    | '/dashboard'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ai-booking'
    | '/convex-showcase'
    | '/dashboard'
    | '/admin/carriers'
    | '/admin/gates'
    | '/admin/terminals'
    | '/admin/trucks'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBookingRoute: typeof AiBookingRoute
  ConvexShowcaseRoute: typeof ConvexShowcaseRoute
  DashboardRoute: typeof DashboardRoute
  AdminCarriersRoute: typeof AdminCarriersRoute
  AdminGatesRoute: typeof AdminGatesRoute
  AdminTerminalsRoute: typeof AdminTerminalsRoute
  AdminTrucksRoute: typeof AdminTrucksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex-showcase': {
      id: '/convex-showcase'
      path: '/convex-showcase'
      fullPath: '/convex-showcase'
      preLoaderRoute: typeof ConvexShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-booking': {
      id: '/ai-booking'
      path: '/ai-booking'
      fullPath: '/ai-booking'
      preLoaderRoute: typeof AiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trucks': {
      id: '/admin/trucks'
      path: '/admin/trucks'
      fullPath: '/admin/trucks'
      preLoaderRoute: typeof AdminTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terminals': {
      id: '/admin/terminals'
      path: '/admin/terminals'
      fullPath: '/admin/terminals'
      preLoaderRoute: typeof AdminTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gates': {
      id: '/admin/gates'
      path: '/admin/gates'
      fullPath: '/admin/gates'
      preLoaderRoute: typeof AdminGatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/carriers': {
      id: '/admin/carriers'
      path: '/admin/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AdminCarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBookingRoute: AiBookingRoute,
  ConvexShowcaseRoute: ConvexShowcaseRoute,
  DashboardRoute: DashboardRoute,
  AdminCarriersRoute: AdminCarriersRoute,
  AdminGatesRoute: AdminGatesRoute,
  AdminTerminalsRoute: AdminTerminalsRoute,
  AdminTrucksRoute: AdminTrucksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
